### ISSUE TITLE
automatisation des envois.

### ISSUE THREAD

**Issue by olivierDevin** [SDIS62/prevarisc-passerelle-platau#11]
Bonjour Kevin,
Plus de souci concernant composer (un bête problème d'installation du composer...)
Y-a-t-il un moyen d'automatiser les envois d'avis de commission ainsi que les prises en compte ? (par exemple générer un fichier avec les id des commissions à envoyer) ?

Bien à vous.

**Comment by kdubuc** [comment]
Pour automatiser l'ensemble des imports / exports, vous pouvez paramétrer un [cron](https://doc.ubuntu-fr.org/cron) représentant une suite logique de commandes à exécuter dans l'ordre (import, export-pec, import-pieces, export-avis).

**Comment by olivierDevin** [comment]
Bonjour Kevin,

J'ai déjà fait le cron, mais je faisais référence à ce qui décrit dans la documentation :

 php bin/platau --config=CHEMIN_RELATIF_VERS_LE_FICHIER_DE_CONFIGURATION.json [--consultation-id=xxx-xxx-xxx] export-pec

Je voulais savoir comment automatiser cette opération qui semble nécessiter un id pour chaque dossier...
________________________________
De : Kévin DUBUC ***@***.***>
Envoyé : mardi 25 janvier 2022 08:52
À : SDIS62/prevarisc-passerelle-platau ***@***.***>
Cc : DEVIN, Olivier ***@***.***>; Author ***@***.***>
Objet : Re: [SDIS62/prevarisc-passerelle-platau] automatisation des envois. (Issue #11)


Pour automatiser l'ensemble des imports / exports, vous pouvez paramétrer un cron<https://doc.ubuntu-fr.org/cron> représentant une suite logique de commandes à exécuter dans l'ordre (import, export-pec, import-pieces, export-avis).

**Comment by kdubuc** [comment]
le paramètre consultation-id est optionnel

**Comment by reversat** [comment]
Bonjour kevin
A quoi sert cet ID ?? et comment l'obtient t on ??

pascal

**Comment by kdubuc** [comment]
cela permet d'envoyer une Prise En Compte sur une consultation spécifique (identifiée par son identifiant Plat'AU xxx-xxx-xxx)
