### ISSUE TITLE
Réutiliser la logique du Datastore de Prevarisc pour stocker les pièces jointes

### ISSUE THREAD

**Issue by A709197** [SDIS62/prevarisc-passerelle-platau#13]
Bonjour,

Un SDIS m'informe que suite aux dernières corrections les pièces jointes Plat'AU sont bien téléchargées, en revanche il est impossible de les ouvrir.
La pièce jointe est bien téléchargée sur la machine, mais sous <PREVARISC_REAL_DATA_PATH>, et pas sous <PREVARISC_REAL_DATA_PATH>/uploads/dossiers/... comme c'est le cas pour les autres pièces jointes.

Quelqu'un d'autre rencontre-t-il le même problème ?

Cordialement,
Maxime Merrien

**Comment by kdubuc** [comment]
quelle est la valeur de ```PREVARISC_PIECES_JOINTES_PATH``` dans la configuration de la passerelle ?

**Comment by A709197** [comment]
La valeur de `PREVARISC_PIECES_JOINTES_PATH` dans la configuration de la passerelle est la même que `PREVARISC_REAL_DATA_PATH` dans la configuration de Prevarisc, dans ce cas _/mnt/prevarisc-data_

**Comment by kdubuc** [comment]
alors il faut rajouter /uploads/dossiers/ dans la configuration, ```PREVARISC_PIECES_JOINTES_PATH``` doit pointer sur l'endroit exact ou sont stockées les pièces jointes

**Comment by A709197** [comment]
Merci Kévin pour la réponse qui est très claire et fonctionne effectivement si Prevarisc utilise le data store SimpleFileDataStore. Je me permet un dernier commentaire afin d'avoir une information.

Nous utilisons par ailleurs un autre data store qui génère dans le chemin vers la pièce jointe une série de dossiers avec des caractères aléatoires ainsi qu'un dossier portant l'identifiant du dossier dans Prevarisc. De ce que je comprend il n'est donc pas possible de renseigner l'information directement dans la configuration de la passerelle. Est-il par contre possible de réutiliser le data store de Prevarisc pour la passerelle ?
Ou de préciser à Prevarisc d'utiliser un data store en particulier pour les dossiers étant récupérés de Plat'AU ?

Merci par avance pour ton retour,
Cordialement,
Maxime Merrien

**Comment by kdubuc** [comment]
ce sera compliqué de réutiliser le DataStore prevarisc, la passerelle étant complètement indépendant de Prevarisc.

Je vais y réfléchir ... Il faudra imaginer un système de plugin à la logique de stockage  https://github.com/SDIS62/prevarisc-passerelle-platau/blob/master/src/Service/Prevarisc.php#L300
