### ISSUE TITLE
429 Too Many Requests

### ISSUE THREAD

**Issue by SDIS91** [SDIS62/prevarisc-passerelle-platau#14]
Bonjour,

Lors de l'import les demandes de consultations en cours dans Prevarisc, on a eu le message d'erreur suivant

" Récupération des consultations versées  ...

In RequestException.php line 113:
                                                                               
  Client error: `POST https://api.aife.economie.gouv.fr/mtes/platau/v6/consul  
  tations/recherche` resulted in a `429 Too Many Requests` response   

import [-c|--config CONFIG]
"

Est ce que le problème vient de platau ou bien de la passerelle ?

Merci d'avance.
SI SDIS91

**Comment by kdubuc** [comment]
Cela vient de Plat'AU, étrange ...
C'est un code qui apparait après avoir envoyé trop de requêtes. Vous avez exécuté la passerelle combien de fois en 24h ?

**Comment by SDIS91** [comment]
Une fois en tache cron à minuit et demi:
30 00 * * * /root/cronjobs/import.sh 2>&1 | mailx -s "Import demandes Plat'au" GSIC-Etudes_Dev@sdis91.fr,prevention@sdis91.fr

**Comment by kdubuc** [comment]
j'ai ouvert un ticket de support plat'au ce matin, j'attends la réponse

**Comment by SDIS91** [comment]
Merci

**Comment by SDIS91** [comment]
Hello

Juste pour vous informer que nous n'avons pas eu cette erreur depuis.

**Comment by kdubuc** [comment]
merci pour le retour ! Je garde néanmoins ce ticket ouvert en attendant la réponse du support plat'au pour qu'ils puissent nous apporter des "guidelines" sur l'interrogation en masse à l'API en évitant le code 429.

Je vous tiens au courant

**Comment by kdubuc** [comment]
Voici la réponse du support

> Des quotas d'appels par application ont été mis en place par PISTE.
> Ils s'appliquent pour chaque application.
> 
> - Un premier quota de **20 appels par seconde** applicable sur les applications en environnement SANDBOX et PRODUCTION
> - Un second quota de 50 000 appels par jour en environnement SANDBOX et de **1 000 000 appels par jour** en environnement de production.
> 
> Les quotas ont pour objectifs de protéger les infrastructures contre les processus automatisés recourant à un nombre excessif de demandes d'API.
> Lorsque le nombre d'appels atteint la limite par seconde ou journalière autorisée, le trafic est bloqué pour l'application concernée, et des réponses avec un statut HTTP 429 sont retournées vers l'appelant.
> Ces quotas doivent donc être pris en compte de manière générale par les SI appelants, et particulièrement pour ceux utilisant des traitements par lot (Batch) pour interagir avec PLAT'AU (quota de 20 appels/seconde).
> 
> Ces informations se trouvent ici https://portail.centre-serveur.din.developpement-durable.gouv.fr/projects/platau/wiki/Quotas_Piste

A surveiller donc si le code 429 revient trop régulièrement (même si je doute qu'un dépassement de ces quotas serait à l'origine du code erreur que vous rencontré).

**Comment by SDIS91** [comment]
Merci

Quand ils disent xx appels par seconde, je présume que c'est par script (import par exemple)?
En tout cas on surveillera l’exécution.

**Comment by kdubuc** [comment]
c'est par identifiant d'application PISTE utilisé (si 5 passerelles utilisent le même client id PISTE, alors elles partageront le même quotas d'utilisation)

**Comment by SDIS91** [comment]
Bonjour

Juste pour information, nous avons eu le message ci-dessus (code 429) cette nuit sachant qu'il n'y a pas de dossiers en attente et rien dans les logs.
