### ISSUE TITLE
Erreur lors du healthcheck - could not find the driver

### ISSUE THREAD

**Issue by nikown** [SDIS62/prevarisc-passerelle-platau#15]
Bonjour,
Lors du healthcheck je tombe l'erreur suivante:

![platau - driver](https://user-images.githubusercontent.com/7092010/151983023-87e57d53-8040-4d85-a2ec-d1e0f2bbf953.png)

Je n'ai trouvé personne avec une erreur similaire, avez vous déjà eu ce message ?

Cordialement,
Nicolas Decor
SDIS 11

**Comment by kdubuc** [comment]
avez vous bien l'extension PHP pdo_mysql disponible et activée sur votre serveur ?

**Comment by aechinard** [comment]
Oui, j'ai eu la même erreur, j'ai du installer pdo_mysql
# docker -phpext-install pdo pdo_mysql
Je crois que c'est cette commande

**Comment by kdubuc** [comment]
pour ceux qui ne sont pas dans un environnement docker :  `$ apt-get install php-mysql` pour debian (ou `$ apt-get install php[VERSION_DE_PHP]-mysql` selon les versions)

**Comment by nikown** [comment]
Je vous remercie, c'était bien cela, j'avais bien pdo_mysql installé mais pas activé dans le php.ini.
