### ISSUE TITLE
Automatisation des commandes d'import

### ISSUE THREAD

**Issue by aechinard** [SDIS62/prevarisc-passerelle-platau#16]
Bonjour,

Les commandes d'import de dossiers et de pièces jointes sont-elles fournies à des fins de test ou sont-elles les commandes à effectuer de façon périodique pour récupérer les données ? Si oui faut-il créer un bash qui va les exécuter tous les jours ?
Il n'y a aucune doc qui précise le travail à faire, la marche à suivre, le fonctionnement ...

Merci pour vos réponses.

**Comment by kdubuc** [comment]
Les commandes fournies par la passerelle représentent les fonctionnalités offertes par la passerelle pour "discuter" avec Plat'AU, ce sont donc des commandes réelles.

Pour automatiser l'execution des commandes d'import / export, vous pouvez configurer un cron comme expliqué précédemment ici https://github.com/SDIS62/prevarisc-passerelle-platau/issues/11#issuecomment-1020900138

**Comment by aechinard** [comment]
Oui, j'ai bien compris cela. A quelle fréquence doit-on les exécuter ?

**Comment by kdubuc** [comment]
Aussi souvent que vous le voulez (tout en gardant en tête les quotas d'utilisation imposés par PISTE - voir https://github.com/SDIS62/prevarisc-passerelle-platau/issues/14#issuecomment-1025616372).

Aussi, toutes les commandes peuvent être exécutées plutôt rapidement SAUF `import-pieces` qui dépendra fortement du débit internet disponible (elle prendra + de temps pour compléter son travail si vous êtes en ADSL). Veillez donc à ne pas lancer un import de pièces toutes les 2 minutes, si le téléchargement d'un dossier peut prendre 5 minutes.
