### ISSUE TITLE
Erreurs lors des commandes 

### ISSUE THREAD

**Issue by aechinard** [SDIS62/prevarisc-passerelle-platau#17]
Cette fois j'ai bien regardé les questions précédemment posée et je ne trouve pas de problème similaire.
J'ai les erreurs suivantes lors de l'exécution des commandes de récupération des pièces jointes, prises En Compte des consultations et l'envoi des avis de commission : 
![image](https://user-images.githubusercontent.com/15011042/151992091-3fb87ec8-9fb9-444f-92ab-b1702551ec12.png)
J'ai mis à jour la passerelle avec la commande git pull

Merci par avance pour vos réponses

**Comment by kdubuc** [comment]
pouvez vous me donner la commande exacte que vous avez écrite dans le terminal ? (en anonymisant l'id de la consultation)

**Comment by aechinard** [comment]
Oui, j'ai récupéré les commandes qui sont dans la doc : 

php bin/platau --config=CHEMIN_RELATIF_VERS_LE_FICHIER_DE_CONFIGURATION.json [--force-non-pec] import-pieces
php bin/platau --config=CHEMIN_RELATIF_VERS_LE_FICHIER_DE_CONFIGURATION.json [--consultation-id=xxx-xxx-xxx] export-pec
php bin/platau --config=CHEMIN_RELATIF_VERS_LE_FICHIER_DE_CONFIGURATION.json [--consultation-id=xxx-xxx-xxx] export-avis

**Comment by aechinard** [comment]
oui, effectivement c'est beaucoup mieux. Merci pour votre aide. J'ai du enlever les informations entre les crochets car j'ai l'erreur suivante : la consultation XXX-XXX-XXX-XXX est introuvable selon les critères de recherche
Puis-je le laisser tel quel sans qu'il n'y ait aucune incidence ?

**Comment by kdubuc** [comment]
vous pouvez l'enlever, le paramètre consultation-id sert uniquement à visé une consultation bien identifié par son ID plat'au
