### ISSUE TITLE
Erreur lors du healthcheck - SQLSTATE [HY000]

### ISSUE THREAD

**Issue by nikown** [SDIS62/prevarisc-passerelle-platau#18]
Bonjour à tous,
Je tombe maintenant sur l'erreur SQL ci-dessous:

![platau](https://user-images.githubusercontent.com/7092010/152115331-b494008b-2a14-4d9e-a24f-30297a012997.png)

"platau" nom de la vm
"sdis11.dmn" suffixe dns sur lequel est enregistré la machine.

On dirait que le healthcheck tente de faire un accès sur une BDD qui serait sur ma VM Platau et non pas sur la VM prevarisc que j'ai renseigné dans le json.

Nicolas Decor

**Comment by kdubuc** [comment]
Il semblerait que l'accès à la base de données Prevarisc ne soit pas autorisé. Avez vous vérifié le mot de passe ?

**Comment by nikown** [comment]
Je suis sur de mon user/mdp/port de ma bdd prevarisc.
J'ai autorisé l'accès distant à ma BDD prevarisc, en commentant la ligne "blind-adress = 127.0.0.1" sur le fichier de conf de mysql.
Je m'aperçois maintenant que sur ma conf prevarisc apache les options platau se sont ajoutés:

![image](https://user-images.githubusercontent.com/7092010/152168266-7025c336-1d6a-4f8a-a1bd-4fc87a8b9e89.png)

Cependant cette conf n'est pas validé lors du restart d'apache sur ma vm prevarisc:

![image](https://user-images.githubusercontent.com/7092010/152168906-cb88ec69-2e2d-448c-abc8-c93fe2b30275.png)

Du côté de platau, j'ai cependant toujours un "access denied"

**Comment by kdubuc** [comment]
J'ai supprimé votre image car on pouvait y retrouver la clé IGN ainsi que le salt Prevarisc.

> Je m'aperçois maintenant que sur ma conf prevarisc apache les options platau se sont ajoutés

Très étrange, il faut "toiletter" votre fichier conf car la configuration de la passerelle n'a rien à y faire.

Pour revenir au problème d'accès, c'est bien un souci de droit de l'utilisateur root sur l'accès à distance.

**Comment by SDIS91** [comment]
Hello

A mon avis il faut créer un utilisateur Platau dans la base de données de prevarisc avec son mot de passe et les privilèges correspondants et le renseigner dans le fichier json de la passerelle. Ce n'est pas très indiqué de connecter des comptes root à la base.

**Comment by kdubuc** [comment]
Ce problème étant lié à un paramétrage de votre base de données Prevarisc, cela ne concerne donc pas la passerelle, je clos le ticket. Merci à @SDIS91 pour les conseils. @nikown n'hésitez pas à continuer ce thread pour nous tenir au courant
