### ISSUE TITLE
Error dans import

### ISSUE THREAD

**Issue by SDIS91** [SDIS62/prevarisc-passerelle-platau#19]
Bonjour

Nous avons reçu un message d'une commune nous informant qu'elle avait déposé un dossier dans Plat'au. En exécutant la commande d'import, nous avons reçu le message suivant:

```
Récupération des consultations versées  ...
In RequestException.php line 113:
                                                                                                                                   
  Server error: `POST [https://api.aife.economie.gouv.fr/mtes/platau/v6/consultations/recherche`](https://api.aife.economie.gouv.fr/mtes/platau/v6/consultations/recherche%60) resulted in a `503 Service Unavailable` response:

**Application is not available**

The application is currently not serving requests at this endpoint. It may not have been started or is still starting.

**Possible reasons you are seeing this page:**

-     The host doesn't exist. Make sure the hostname was typed correctly and that a route matching this hostname exists.
-     The host exists, but doesn't have a matching path. Check if the URL path was typed correctly and that the route was created using the desired path.
-     Route and path matches, but all pods are down. Make sure that the resources exposed by this route (pods, services, deployment configs, etc) have at least one pod running.

```
Est-ce que l'erreur vient du serveur de Plat'au?

Pour information, la commande exécutée en cron quelques heures avant a retourné le message habituel d’absence de dossiers.

Merci

**Comment by kdubuc** [comment]
Plat'AU semble indisponible en effet. Que donne le healthcheck ?

**Comment by SDIS91** [comment]
Bonjour

Apparemment, ça marche à nouveau. Mais en exécutant l'import nous avons reçu le message habituel "Pas de consultations nous concernant. On vérifiera plus tard si il y en a de nouvelles !" alors qu'une mairie nous a assuré avoir déposé un dossier. 
Y a-t-il un moyen de vérifier?

**Comment by kdubuc** [comment]
La commande import récupère toutes les consultations dans un état _Non Traitée_, les autres états correspondent à une attente de PEC, ou d'avis. Si la recherche ne trouve rien, alors aucun dossier n'est en attente d'une prise en compte. Pouvez vous voir avec la mairie l'ID Acteur utilisé pour vous identifier ? ainsi que l'ID de la consultation ?
