### ISSUE TITLE
Erreur lors du healthcheck

### ISSUE THREAD

**Issue by SDIS52Infotrans** [SDIS62/prevarisc-passerelle-platau#22]
Bonjour,
Nous sommes en train de mettre en place la passerelle prevarisc/platau.
Un serveur dédié à la passerelle a été créé (Debian 11, php 7.4).

La passerelle à été installée a l'aide de git et composer, cependant la commande healthcheck échoue.
![Annotation 2022-03-22 104911](https://user-images.githubusercontent.com/23100541/159453263-67d3975a-c98f-4056-be6c-7a47895296ae.png)

J'ai vérifié la communication entre la passerelle et le serveur prevarisc, à ce niveau là aucun problème.
Le fichier de configuration (que j'ai placé dans /var/www/prevarisc-passerelle-platau) est renseigné avec les bonnes infos.
Ayant lu les autres tickets j'ai vu que ça ne marchait pas si l'extension pdo-mysql n'était pas activée, je l'ai donc activée de mon coté mais aucun changement.

Merci d'avance pour votre aide.
Anthoine MONFILS, SDIS52

**Comment by kdubuc** [comment]
effectivement, le message d'erreur n'est pas parlant, mais je peux vous dire que vous avez un problème au niveau du fichier de configuration. Pouvez vous le poster ici en anonymisant les données sensibles (mot de passe, ID acteur ...)

**Comment by SDIS52Infotrans** [comment]
Voici le fichier de configuration anonymisé : 

```
{
    "platau.options": {
        "PISTE_CLIENT_ID": "piste_id",
        "PISTE_CLIENT_SECRET": "secret",
        "PLATAU_ID_ACTEUR_APPELANT": "id"
    },
    "prevarisc.options": {
        "PREVARISC_DB_NAME": "prevarisc",
        "PREVARISC_DB_USER": "user",
        "PREVARISC_DB_PASSWORD": "password",
        "PREVARISC_DB_HOST": "ip",
        "PREVARISC_DB_DRIVER": "pdo_mysql",
        "PREVARISC_DB_CHARSET": "utf8",
        "PREVARISC_DB_PORT": 3306,
        "PREVARISC_DB_PLATAU_USER_ID": 0,
        "PREVARISC_PIECES_JOINTES_PATH": "\var\www\prevarisc\public\data\uploads\pieces-jointes"
    }
}
```

**Comment by SDIS52Infotrans** [comment]
C'était bien ça, merci beaucoup de votre aide.
