### ISSUE TITLE
Le message d'erreur "La consultation n'existe pas dans Prevarisc" est peu explicite

### ISSUE THREAD

**Issue by SDIS91** [SDIS62/prevarisc-passerelle-platau#23]
Bonjour

A l’exécution du script ExportPec, nous avons eu le message suivant:
"Problème lors du traitement de la consultation : La consultation n'existe pas dans Prevarisc"
Il serait bon d'ajouter `$consultation_id` au message pour plus de clarté.

Merci

**Comment by kdubuc** [comment]
exact, je vais rajouter cette information dans le message d'erreur levé ici : https://github.com/SDIS62/prevarisc-passerelle-platau/blob/master/src/Service/Prevarisc.php#L48

Merci pour vos retours, et n'hésitez pas, si jamais, à contribuer directement au code via les Pull Request 😉
