### ISSUE TITLE
Importation consultations Prevarisc

### ISSUE THREAD

**Issue by nikown** [SDIS62/prevarisc-passerelle-platau#25]
Bonjour,
Pourrais je savoir où s'importent les consultations sur Prevarisc lors de la commande:
`$ php bin/platau --config=CHEMIN_RELATIF_VERS_LE_FICHIER_DE_CONFIGURATION.json import`
Cordialement,
Nicolas Decor
SDIS11 - Service SITC

**Comment by kdubuc** [comment]
Les consultations arrivent directement dans la base de données Prevarisc avec un ID PLATAU renseigné
