### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by SDIS91** [SDIS62/prevarisc-passerelle-platau#26]
Bonjour

Depuis la maintenance de Piste hier, nos appels à l'application retourne un 403 forbidden. Le healthecheck retourne:
 Client error: `GET https://api.aife.economie.gouv.fr/mtes/platau/v6/healthcheck` resulted in a `403 Forbidden` response

Est-ce que vous rencontré ce problème?

Merci

**Comment by CFX-SDIS33** [comment]
Bonjour,

J'ai rencontré le même souci.

Pour le résoudre, il faut : 
- vous connecter sur l'application PISTE
- consentir les CGU des API Plat'AU (j'ai sélectionné les V6, V7 et V8)
- modifier votre application créée sur le compte PISTE, en sélectionnant les API PLAT'AU dont on a précédemment consenti les CGU

**Comment by kdubuc** [comment]
Je rencontre un 403 aussi.
Après vérification, l'ensemble des API liées aux applications PISTE a disparu (validation CGU, approbation par l'équipe Plat'AU ...).

Une perte de données côté PISTE est à envisager.

J'ai relancé la procédure de validation de mon côté.

Je vous tiens au courant !

**Comment by kdubuc** [comment]
J'ai recu ce mail ce matin : 

> Vous êtes inscrit avec succès à PISTE pour accéder à l'application Plat'AU xxxxxxxxx.

Le healthcheck me donne à nouveau des 200. Vous pouvez confirmer de votre côté ?

**Comment by CFX-SDIS33** [comment]
Je confirme que l'API Plat'AU est de nouveau fonctionnelle (nos scripts de cette nuit sont passés correctement).
