### ISSUE TITLE
Problème d'extension sur les PJ depuis la migration à Plat'AU V7

### ISSUE THREAD

**Issue by CFX-SDIS33** [SDIS62/prevarisc-passerelle-platau#28]
Bonjour

Merci pour la mise à jour. L'import s'est bien passé, l'import-pieces a retrouvé des dossier mais la réponse contenait la notice suivante:
`PHP Notice:  Undefined index: extension in /var/www/html/prevarisc-passerelle-platau/src/Service/PlatauPiece.php on line 45`
répétée deux fois.
Est-ce que cela pourrait venir de fichiers avec des extensions inconnues (ou sans extension)?

_Originally posted by @SDIS91 in https://github.com/SDIS62/prevarisc-passerelle-platau/issues/27#issuecomment-1156564696_

**Comment by kdubuc** [comment]
J'ai mis à jour la passerelle pour gérer un peu mieux la RFC 6266 détaillant le fonctionnement de l'entête Content-Disposition afin de récupérer correctement les extensions. Voir https://github.com/SDIS62/prevarisc-passerelle-platau/commit/e90a2ff56ee6f06f3bc7d630345c7364e2d84be4

Si vous rencontrez à nouveau le problème, mettez moi vos retours ici et j'ouvrirai à nouveau le ticket
