### ISSUE TITLE
A propos du changement d'avis de la commission (amélioration)

### ISSUE THREAD

**Issue by SDIS91** [SDIS62/prevarisc-passerelle-platau#29]
Bonjour

Quand il nous arrive de changer d'avis sur un dossier issus de Plat'AU, nous lançons les commandes d'export manuellement en ajoutant l'id consultation du dossier.
Est-ce qu'il y aurait moyen d’intégrer le vérification des changements d'avis dans les scripts d'export qui s’exécutent en cron?
De notre coté, nous allons regarder si c'est possible.

Merci

**Comment by kdubuc** [comment]
La passerelle étant assez flexible sur ce qu'elle peut faire avec Plat'AU, ce serait à vos jobs d'import (à savoir vos cron) de s'adapter au métier.
Pouvez vous me détailler le cas particulier du changement d'avis de commission après un envoi sur Plat'AU ?

**Comment by SDIS91** [comment]
Concernant un dossier particulier, la prévention a envoyé un avis favorable mais quelques jours plus tard, il ont changé l'avis en défavorable, mais évidemment l'export  programmé ne l'a pas envoyé. Nous avons du lancé l'export manuellement en ajoutant --consultation-id=xxx. Ce n'est pas vraiment bloquant mais ça veut dire que la prévention doit nous prévenir de lancer la commande manuellement.
On se demande s'il y a un moyen de repasser sur les dossiers Plat'au pour vérifier si des avis ont changé, mais cela suppose qu'il y ait une sorte d'historique des avis.
