### ISSUE TITLE
Récupération des pièces-jointes

### ISSUE THREAD

**Issue by SDIS52Infotrans** [SDIS62/prevarisc-passerelle-platau#30]
Bonjour,
J'ai des erreurs pour la récupération des pièces-jointes de 3 consultations.
J'ai une ligne d'erreur par pièce-jointe j'ai l'impression. Voici un exemple :
![image](https://user-images.githubusercontent.com/23100541/176366392-b6ed64c7-0a7d-4d74-b8a6-cd728688f8b0.png)
A savoir que c'est la première fois que nous avons des pièces-jointes à récupérer depuis la mise en place de la V7.
Cela fonctionnait sur la V6.
Merci d'avance.

**Comment by kdubuc** [comment]
avez vous récupéré la mise à jour https://github.com/SDIS62/prevarisc-passerelle-platau/commit/e90a2ff56ee6f06f3bc7d630345c7364e2d84be4 avant l'import de pièces ?
