### ISSUE TITLE
message erreur sur le transfert de dossier

### ISSUE THREAD

**Issue by atichit** [SDIS62/prevarisc-passerelle-platau#32]
bonjour,
j'ai l'erreur suivante qui apparait lorsque j'effectue une importation de dossier depuis la plateforme plat'au

![image](https://user-images.githubusercontent.com/24435008/188593041-9715b9ec-b6f4-4c43-860e-f46a93313977.png)
![Capture d’écran 2022-09-06 105925](https://user-images.githubusercontent.com/24435008/188593346-57dec630-53e5-44a7-bdbc-7da839a9eb69.png)

je vous remercie par avance pour une eventuelle solution

**Comment by kdubuc** [comment]
Avez vous la dernière version de la passerelle (notamment le fix https://github.com/SDIS62/prevarisc-passerelle-platau/commit/e90a2ff56ee6f06f3bc7d630345c7364e2d84be4) ?

**Comment by atichit** [comment]
bonjour, 

effectivement la mise à jour règle le problème. 

merci de votre retour 

bonne journée 

cordialement 



De: "Kévin DUBUC" ***@***.***> 
À: "SDIS62/prevarisc-passerelle-platau" ***@***.***> 
Cc: "TICHIT Alain SIC" ***@***.***>, "Author" ***@***.***> 
Envoyé: Mardi 6 Septembre 2022 11:40:47 
Objet: Re: [SDIS62/prevarisc-passerelle-platau] message erreur sur le transfert de dossier (Issue #32) 





Avez vous la dernière version de la passerelle (notamment le fix [ https://github.com/SDIS62/prevarisc-passerelle-platau/commit/e90a2ff56ee6f06f3bc7d630345c7364e2d84be4 | e90a2ff ] ) ?
