### ISSUE TITLE
Absence d'export des PEC et des avis

### ISSUE THREAD

**Issue by A709197** [SDIS62/prevarisc-passerelle-platau#33]
Bonjour à tous,

2 SDIS nous ont signalé l'absence de remonté des PEC et des avis. Le message indique qu'il est impossible d'envoyer la PEC/l'avis car l'information n'est pas renseignée dans Prevarisc.

Cependant dans la base de données de Prevarisc, l'information est correctement renseignée. Après analyse chez l'un des SDIS, il s'avère que les conditions telles qu'[ici](https://github.com/SDIS62/prevarisc-passerelle-platau/blob/master/src/Command/ExportPEC.php#L70) ne sont jamais valides car les champs remontés depuis Prevarisc (en l'occurrence INCOMPLET_DOSSIER et AVIS_DOSSIER_COMMISSION) sont de type int() et non string.

Quelqu'un d'autre rencontre-t-il ce même problème ?

Cordialement,
Maxime Merrien

**Comment by kdubuc** [comment]
il semblerait que la ```doctrine/dbal``` cast automatiquement, ou pas, en string en fonction de la base de données.
J'ai poussé une mise à jour avec un cast explicite : https://github.com/SDIS62/prevarisc-passerelle-platau/commit/9b2433ce221d5b20f6716bb42dcc56861a7e501b
Pouvez vous tester de votre côté ?

**Comment by A709197** [comment]
Bonjour Kévin,

Je viens de tester la mise à jour, et le test est concluant de mon côté.
Merci pour la correction !

Cordialement,
Maxime Merrien
