### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by SDIS91** [SDIS62/prevarisc-passerelle-platau#34]
Bonjour

Cela fait quelques jours que nous avons cette erreur dans nos appels Plat'au.
Ils ne seraient pas passés à la version 8 sans nous prévenir par hasard?
Je cite Kevin dans un ticket #27 de juin dernier:

> Après contact avec le support Plat'AU, la v6 est retirée définitivement en faveur de la v7 (qui sera retirée à son tour en septembre de cette année, dans 3 mois)

Merci

**Comment by kdubuc** [comment]
Il était prévu que la version 7 soit décommissionnée ce mois ci.

Vous pouvez passer à la v8 grâce à cette mise à jour https://github.com/SDIS62/prevarisc-passerelle-platau/commit/4858d78177852a7e555a27be68a476ae83c1e3d5

**Comment by SDIS91** [comment]
En effet c’était ça.
A ce propos, il y a moyen de recevoir des notifications de commit?

Merci

**Comment by kdubuc** [comment]
Oui vous pouvez "watch" le dépôt pour recevoir des notifications Github sur l'activité de la passerelle. https://docs.github.com/en/rest/activity/watching
