### ISSUE TITLE
Non réception de consultations

### ISSUE THREAD

**Issue by nmeucci** [SDIS62/prevarisc-passerelle-platau#36]
Bonjour, l'urbanisme nous a consulté sur deux dossiers avec l'ID Plat'Au OQ5-03D-RMK et LE7-YWD-EEK (environnement _mtes_ en v8).

Or la commande _import_ ne les réceptionne pas et renvoie :
```
Récupération des consultations versées...
Consultation [ID] déjà existante dans Prevarisc
```

Donc aucune erreur du connecteur, idem côté urbanisme (JSON à disposition). Peut-être est-ce du côté de Plat'Au ?

**Comment by kdubuc** [comment]
Le message indique que les deux consultations ont bien été importées dans la base de données de Prevarisc. Il faudrait faire une vérification dans la base en faisant une requête sur la table dossiers et une condition sur les champs ID_PLATAU

**Comment by nmeucci** [comment]
Merci Kevin.

Au cas où il y ait une ambiguïté : le message de sortie de la commande _import_ parle en effet de consultations déjà existantes mais bien évidemment pas des deux dont je fais état. Ce log mentionne des précédentes. Si par contre on parle d'un message de Plat'Au, c'est erroné : je confirme aucun résultat pour les deux ID Plat'Au en question dans la base de données. De plus, au cas où les dossiers eussent été créés sans ID Plat'Au renseigné, j'ai recherché les derniers dossiers par leur propre ID : ce sont les consultations récupérées précédemment, il n'y a aucun dossier récent sans ID Plat'Au. J'ai bien en base de données ce que l'interface et le log de la commande _import_ montrent.

Le ticket #38 semble faire état d'un éventuel délai, parfois assez long, avant la réception de certaines consultations : peut-être sommes-nous dans ce cas. Je remonterai l'info le cas échéant.

**Comment by kdubuc** [comment]
Nicolas, peux tu me confirmer que ton ID ACTEUR se termine par R38-8LM ?

**Comment by kdubuc** [comment]
Nicolas, peux tu me confirmer que ton ID ACTEUR se termine bien par : R38-8LM ?

**Comment by nmeucci** [comment]
Tout à fait !

**Comment by kdubuc** [comment]
Ok donc les consultations contiennent le bon destinataire.

Quel est l'état des consultations pour le service instructeur ? La passerelle attend un état "Non Traitée" pour récupérer des consultations .

**Comment by nmeucci** [comment]
Pas certain que cela réponde à ta question, j'ai reçu des JSON de l'urbanisme avec nomEtatConsultation d'ID 1 et lib "Versée."

**Comment by kdubuc** [comment]
dans ton fichier de configuration, tu peux me confirmer que c'est bien ton ID Acteur xxx-R38-8LM dans PLATAU_ID_ACTEUR_APPELANT ?

**Comment by nmeucci** [comment]
Yes Sir ! Qui est bien renseigné côté urba également.

J'aurais dû le préciser mais parfois je reçois des consultations donc on est bon niveau config. Suis gêné par le côté "aléatoire", "erratique", car j'essaie de proscrire ces termes en informatique...

**Comment by kdubuc** [comment]
@nmeucci on pourra voir ça directement lundi prochain ;)

**Comment by kdubuc** [comment]
Après avoir creusé avec ton fichier de xonfiguration @nmeucci, le problème de réception aléatoire devrait être fix par le commit https://github.com/SDIS62/prevarisc-passerelle-platau/commit/c6d8dc4e94be3c02d957233d667fb5a422cf909f ! Peux tu me confirmer de ton côté ?

**Comment by nmeucci** [comment]
Merci, je teste ça dès ton fix publié pour rétrocompatibilité PHP < 8.

**Comment by kdubuc** [comment]
C'est ok depuis https://github.com/SDIS62/prevarisc-passerelle-platau/commit/24eb4ab508e5b20178674eda4fb0d1202742f5cd ;)

**Comment by nmeucci** [comment]
Lors du healthcheck :

> PHP Parse error:  syntax error, unexpected ')', expecting '|' or variable (T_VARIABLE) in /var/www/html/connecteur/bin/platau on line 34

**Comment by kdubuc** [comment]
J'ai mis à jour la branche principale

**Comment by nmeucci** [comment]
J'ai récupéré des consultations merci !

**Comment by nmeucci** [comment]
Bonjour, il y a au moins 3 consultations que le connecteur ne récupère pas (envoyées par l'urbanisme vendredi passé : O38-6DV-DWK, KNG-Q16-PDL et LPG-QVZ-V5L).

**Comment by kdubuc** [comment]
Peux tu utiliser la commande details-consultation pour vérifier leur état ?

**Comment by nmeucci** [comment]
Je n'avais pas cette commande puis d'avoir mis à jour le connecteur j'ai pu récupérer 2 des 3 consultations (état "Versée"), merci.

Pour la 3ème, KNG-Q16-PDL, la commande me retourne qu'elle est introuvable.

**Comment by kdubuc** [comment]
La consultation n'existe pas pour plateau. A voir avec le service instructeur . Je clos le ticket pour le moment.
