### ISSUE TITLE
Problème alimentation champ Demandeur

### ISSUE THREAD

**Issue by CFX-SDIS33** [SDIS62/prevarisc-passerelle-platau#37]
Bonjour,

Nous souhaitons vous soumettre un problème relatif à l'alimentation du champ Demandeur de Prevarisc par la passerelle.

Le service instructeur qui nous consulte est inséré 2 fois :
- dans le champ demandeur : à supprimer et à remplacer si possible par l'identification du maître d'ouvrage
- dans le champ service instructeur : à conserver

**Comment by kdubuc** [comment]
Les champs utilisent deux données distinctes de Plat'AU (voir https://github.com/SDIS62/prevarisc-passerelle-platau/blob/master/src/Command/ImportConsultations.php#L73-L74) :
- Champ demandeur : Identifiant Plat'AU du service Consultant ;
- Service instructeur : Identifiant Plat'AU du Service Instructeur.

A voir avec le service qui vous consulte si il place cette info deux fois ?

**Comment by CFX-SDIS33** [comment]
Ok, merci pour ces précisions.
Toutefois, nous ne comprenons pas vraiment la nuance entre consultant et instructeur...

Quoi qu'il en soit, on va se rapprocher des services consultants pour savoir comment ils alimentent ces deux champs.
D'autre part, existe-t-il un champ Demandeur (maître d'ouvrage) dans Plat'AU, que l'on pourrait éventuellement récupérer ?

**Comment by kdubuc** [comment]
Après contact avec le support Plat'AU : 
> Non cela n'existe pas sur plat'au. En revanche le champ "txObjetDeLaConsultation" est un texte descriptif de la consultation qui pourrait être utilisé par le service consultant lors de la création de la consultation. 

Il faudrait prendre contact avec le service instructeur pour lui donner des consignes de création.
