### ISSUE TITLE
Problème de réception de consultations Plat'AU, d'envoi de PEC et d'avis

### ISSUE THREAD

**Issue by CFX-SDIS33** [SDIS62/prevarisc-passerelle-platau#38]
Bonjour,

Comme évoqué lors de la visio hebdomadaire Synchro-éditeurs DématADS de la semaine dernière, nous rencontrons des soucis pour la réception de consultations Plat'AU, ainsi que pour l'envoi de PEC ou d'avis.

En voici quelques exemples :
- Identifiant Plat'AU **LZV-WW0-66O** : consultation envoyée par le service instructeur le 01/06/2022, réception du dossier le 02/06/2022, PEC envoyée le 17/06/2022 et **dossier en attente d'avis seulement jusqu'au 28/06/2022.**
- Identifiant Plat'AU **KRJ-55M-54O** : consultation envoyée par le service instructeur le 01/06/2022, réception du dossier le 02/06/2022, **PEC envoyée seulement le 13/07/2022 alors que renseignée bien avant dans Prevarisc (date de l'avis au 24/06/2022) et dossier jamais en attente d'avis**.
- Identifiant Plat'AU **L9G-4M5-5YO** : consultation envoyée par le service instructeur le 02/06/2022, **réception du dossier seulement le 22/06/2022**, PEC envoyée le 23/06/2022 et **dossier jamais en attente d'avis**.
- Identifiant Plat'AU **OX1-9PX-PDO** : consultation envoyée par le service instructeur le 02/06/2022, **réception du dossier seulement le 13/07/2022**, PEC envoyée le 21/07/2022 et **dossier jamais en attente d'avis**.
- Identifiant Plat'AU **L2J-GGZ-QML** : consultation envoyée par le service instructeur le 03/06/2022, **réception du dossier seulement le 13/07/2022**, PEC envoyée le 25/07/2022 et **dossier en attente d'avis uniquement le 13/10/2022**.
- Identifiant Plat'AU **L9R-9QV-PEK** : consultation envoyée par le service instructeur le 09/06/2022, **réception du dossier seulement le 22/06/2022**, PEC envoyée le 23/06/2022 et **dossier en attente d'avis uniquement le 29/06/2022 et le 30/06/2022**.
- Identifiant Plat'AU **KNV-EWY-02L** : consultation envoyée par le service instructeur le 17/06/2022, réception du dossier le 18/06/2022, PEC envoyée le 21/06/2022 et **dossier en attente d'avis uniquement le 21/06/2022, le 22/06/2022 et le 04/08/2022**.

Pour information, ces exemples proviennent de consultations envoyées par Bordeaux Métropole qui utilise le logiciel Cart@DS.

En vous remerciant par avance de votre analyse en lien avec le support Plat'AU pouvant expliquer ces comportements bizarres des intéractions de la passerelle avec Plat'AU.

**Comment by kdubuc** [comment]
Une demande au support Plat'AU a été envoyé. Je vous tiens au courant.

**Comment by LD-SDIS33** [comment]
Pouvez vous transmettre le réponse faite par la synchro éditeurs sur le ticket incident, confirmée lors de la visio du 29 novembre
Merci

**Comment by kdubuc** [comment]
Voici la réponse du support pour la consultation KNV-EWY-02L : 

> Le status de la consultation reste bien à l'état "Pris en compte, en cours de traitement" (équivalent à "en attente d'avis" dans votre solution) tant qu'aucune action n'a été faite sur la consultation. Par exemple pour la consultation KNV-EWY-02L nous avons l'état "Pris en compte, en cours de traitement" entre le 21/06 (date création de la pec) et le 4/08 (date de création de l'avis)


Extraction de la base Plat'AU :
```
idConsultation:"KNV-EWY-02L"
idActeurGenerateur:"XL9-7V3-MKD"
idServiceConsultant:"XL9-7V3-MKD"
idServiceConsulte:"XL9-GQV-QGO"
dtConsultation:2022-06-16T22:00:00.000+00:00
dtEmission:2022-06-16T22:00:00.000+00:00
delaiDeReponse:2

nomEtatConsultation.idNom:3
nomEtatConsultation.libNom:"Prise en compte (en cours de traitement)"
hdProductionNotification:2022-06-17T11:13:13.215+00:00

pecMetiers.noVersion:2
hdDebutVersion:2022-06-21T01:00:12.059+00:00
hdFinVersion:2022-08-04T02:00:15.603+00:00
```

Je n'ai eu qu'un exemple par le support.
Est ce que cela correspond à ce que vous avez constaté ? La PEC a bien été reçue en temps et en heure, qui est suivi par l'avis le 4 aout ?

**Comment by CFX-SDIS33** [comment]
Comme indiqué dans ma déclaration d'incident, l'analyse des logs de communication entre la passerelle et Plat'AU fait état que "dossier en attente d'avis uniquement le 21/06/2022, le 22/06/2022 et le 04/08/2022" alors que l'avis a pu être renseigné dans Prevarisc n'importe quand entre le 22/06 et 04/08...

**Comment by kdubuc** [comment]
Peut'on organiser un test grandeur nature avec votre service instructeur ?
Nous validerons étape par étape les échanges avec la passerelle.

**Comment by LD-SDIS33** [comment]
Bonsoir Kevin,
Je vous propose pour une meilleure efficience de prendre contact directement avec inetum éditeur de cart'ads logiciel du service instructeur de Bordeaux Métropole, afin de faire ce test grandeur nature 
Bien sûr, Christophe Friloux restera disponible pour accompagner la démarche autant que nécessaire et aboutir à plus de compréhension sur le fonctionnement des flux montant et descendant.

Par ailleurs, la mise à jour du connecteur en V9 est elle réalisée ? Ainsi que la possibilité de renvoi de pièces jointes ?

**Comment by kdubuc** [comment]
le commit https://github.com/SDIS62/prevarisc-passerelle-platau/commit/c6d8dc4e94be3c02d957233d667fb5a422cf909f devrait solutionner le problème de réception des consultations !

Pouvez vous me confirmer ? 

> Par ailleurs, la mise à jour du connecteur en V9 est elle réalisée ?

Oui, grâce à une contribution de @SDIS91 !

> Ainsi que la possibilité de renvoi de pièces jointes ?

à suivre ici : https://github.com/SDIS62/prevarisc-passerelle-platau/issues/21

**Comment by LD-SDIS33** [comment]
Est ce que cela devrait également solutionner les remontées pec et avis vers plat'au ?

**Comment by kdubuc** [comment]
Oui, nous avons mis à jour la méthode de récupération des consultations, ce qui nous permet de mieux tracer les états de traitement plus précisément.

**Comment by LD-SDIS33** [comment]
Merci ce point d'avancement. Retour de notre part dès que possible

**Comment by LD-SDIS33** [comment]
Est ce qu'un de vous peut déjà confirmer des améliorations du fonctionnement de la demat après mise à jour  du connecteur  ?

**Comment by kdubuc** [comment]
de notre côté, fonctionnel au 62

**Comment by LD-SDIS33** [comment]
Mise à jour du connecteur faite le 13 février. 
Pour les consultations, ça descent fort entre Plat'au et Prevarisc !!! 
150 dossiers avec id consultation, en une semaine, sont arrivées. 
On peut raisonnablement affirmer que la mise à jour est fonctionnelle.
Nous sommes en évaluation avec Bordeaux Métropole, actuellement, du bon fonctionnement également sur les PEC et Avis rendus. Nous vous informerons asap du résultat.
Votre implication ainsi que celle de l'équipe technique Plat'au, ont été d'un grand soutien dans une période de montée en charge de la demat, pour nous, qui n'a pas été simple.
Soyez en collectivement remerciés.

**Comment by kdubuc** [comment]
Heureux de pouvoir marquer ce ticket comme résolu :) Merci pour votre message.
