### ISSUE TITLE
ServiceProvider\FileStorageSystem

### ISSUE THREAD

**Issue by SDIS91** [SDIS62/prevarisc-passerelle-platau#4]
Hello

A la demande du Healthcheck nous avons l'erreur suivante:
PHP Fatal error:  Uncaught Error: Class "App\ServiceProvider\FileStorageSystem" not found in /var/www/html/prevarisc-passerelle-platau/src/Console.php:21

En effet il n'y a pas de FileStorageSystem dans le dossier ServiceProvider

**Comment by A709197** [comment]
Bonjour,

En effet, nous avons d'ailleurs supprimé ce service qui ne semble plus utilisé dans [cette PR](https://github.com/SDIS62/prevarisc-passerelle-platau/pull/3).
@kdubuc Pouvez-vous vérifier la modification ?

**Comment by SDIS91** [comment]
L'erreur a été corrigée mais nous avons une erreur 404:

Client error: `GET https://api.aife.economie.gouv.fr/mtes_preprod/platau/v4/healthcheck` resulted in a `404 Not Found` response

Probablement à cause de mtes_preprod.

**Comment by kdubuc** [comment]
> Bonjour,
> 
> En effet, nous avons d'ailleurs supprimé ce service qui ne semble plus utilisé dans [cette PR](https://github.com/SDIS62/prevarisc-passerelle-platau/pull/3). @kdubuc Pouvez-vous vérifier la modification ?

Modification intégrée, merci !

> L'erreur a été corrigée mais nous avons une erreur 404:
> 
> Client error: `GET https://api.aife.economie.gouv.fr/mtes_preprod/platau/v5/healthcheck` resulted in a `403 Forbidden` response
> 
> Probablement à cause de mtes_preprod.

Vous réalisez vos tests sur quel environnement ?

**Comment by SDIS91** [comment]
L'environnement prod. Mais peut-être que nous anticipons un peu.

**Comment by kdubuc** [comment]
La passerelle sera mise à jour avec la dernière version de Plat'AU en production (un point de discussion peut être retrouvé ici https://github.com/SDIS62/prevarisc-passerelle-platau/pull/2).

Je me permet de fermer le ticket 😉
