### ISSUE TITLE
Problème export avis : Command failed with error 10334 (BSONObjectTooLarge)

### ISSUE THREAD

**Issue by CFX-SDIS33** [SDIS62/prevarisc-passerelle-platau#41]
Bonjour,

Depuis le 29/12, nous rencontrons l'erreur suivante (quand ce n'est pas l'erreur `Connection refused`) lors de la commande d'export des avis : 

  `In RequestException.php line 113:`
    
    `Server error: `POST https://api.aife.economie.gouv.fr/mtes/platau/v9/consul
    tations/recherche?numeroPage=0` resulted in a `500 Internal Server Error` r
    esponse:
    {"message":"Command failed with error 10334 (BSONObjectTooLarge): 'BSONObj
    size: 20742376 (0x13C80E8) is invalid. Size must be between 0 and 16793600(
    16MB) First element: operationTime: Timestamp(1673895610, 41)' on server mo
    ngo-mongodb-0.mongo-mongodb-headless.prod.svc.cluster.local:27017. The full
     response is {\"operationTime\": {\"$timestamp\": {\"t\": 1673895570, \"i\"
    : 11}}, \"ok\": 0.0, \"errmsg\": \"BSONObj size: 20742376 (0x13C80E8) is in
    valid. Size must be between 0 and 16793600(16MB) First element: operationTi
    me: Timestamp(1673895610, 41)\", \"code\": 10334, \"codeName\": \"BSONObjec
    tTooLarge\", \"$clusterTime\": {\"clusterTime\": {\"$timestamp\": {\"t\": 1
    673895610, \"i\": 74}}, \"signature\": {\"hash\": {\"$binary\": {\"base64\"
    : \"DRJtzjUZ7QWYuZoU+FvvuW5jn2Q=\", \"subType\": \"00\"}}, \"keyId\": 71260
    72504728158210}}}; nested exception is com.mongodb.MongoCommandException: C
    ommand failed with error 10334 (BSONObjectTooLarge): 'BSONObj size: 2074237
    6 (0x13C80E8) is invalid. Size must be between 0 and 16793600(16MB) First e
    lement: operationTime: Timestamp(1673895610, 41)' on server mongo-mongodb-0
    .mongo-mongodb-headless.prod.svc.cluster.local:27017. The full response is
    {\"operationTime\": {\"$timestamp\": {\"t\": 1673895570, \"i\": 11}}, \"ok\
    ": 0.0, \"errmsg\": \"BSONObj size: 20742376 (0x13C80E8) is invalid. Size m
    ust be between 0 and 16793600(16MB) First element: operationTime: Timestamp
    (1673895610, 41)\", \"code\": 10334, \"codeName\": \"BSONObjectTooLarge\",
    \"$clusterTime\": {\"clusterTime\": {\"$timestamp\": {\"t\": 1673895610, \"
    i\": 74}}, \"signature\": {\"hash\": {\"$binary\": {\"base64\": \"DRJtzjUZ7
    QWYuZoU+FvvuW5jn2Q=\", \"subType\": \"00\"}}, \"keyId\": 712607250472815821
    0}}}","uuid":"f4b69a98-32f0-4657-9a5a-43aa817990b8","codeErreur":500}`

Avez-vous une explication ?

D'avance merci.

**Comment by kdubuc** [comment]
C'est un problème retourné pr Plat'AU. Pour aller plus loin dans la technique, c'est leur base de données MongoDB qui dit que ce qu'il doit vous renvoyer est trop gros, et qu'il abandonne la requête.

Je fais un ticket sur le support plat'au.

**Comment by kdubuc** [comment]
L'équipe Plat'AU a confirmé qu'un nombre trop grand peut faire planter leur système.
Grâce au patch https://github.com/SDIS62/prevarisc-passerelle-platau/commit/d8e4e423d56be86622f51db848c374e182b5b0cc la passerelle peut essayer de contourner cela. Pouvez vous me faire un retour sur le bon fonctionnement de votre côté ?

**Comment by LD-SDIS33** [comment]
Merci pour votre réponse. A regret de ne pouvoir faire retour avant mi fevrier sur ce patch.

**Comment by kdubuc** [comment]
poke @LD-SDIS33 ?

**Comment by LD-SDIS33** [comment]
Résolu, peut être clôturé
