### ISSUE TITLE
Erreurs PHP

### ISSUE THREAD

**Issue by SDIS91** [SDIS62/prevarisc-passerelle-platau#42]
Bonjour

Depuis les derniers commits, nous recevons des erreurs PHP quand les taches se lancent.
- premiere erreur, prevarisc-passerelle-platau/bin/platau on line 27: `catch(Exception) {`. Je crois qu'il faut ajouter une variable: `catch(Exception $e) {` (je peux faire un PR).
- Quand j'ajoute $e l'erreur change en : PHP Fatal error:  Uncaught Error: Class 'GuzzleRetry\GuzzleRetryMiddleware' not found in /var/www/html/prevarisc-passerelle-platau/src/Service/PlatauAbstract.php:52

**Comment by kdubuc** [comment]
- Avez vous fait un ```composer update``` ? 
- Quelle version de PHP avez vous ?

**Comment by SDIS91** [comment]
Je viens de le faire, j'ai toujours l'erreur du catch et quand je la corrige j'ai:
PHP Parse error:  syntax error, unexpected 'private' (T_PRIVATE), expecting variable (T_VARIABLE) in /var/www/html/prevarisc-passerelle-platau/src/Command/DetailsConsultation.php on line 16

Nous somme en PHP 7.4

**Comment by kdubuc** [comment]
Avez vous la possibilité de passer en PHP 8.0 ?

**Comment by SDIS91** [comment]
Oui, si ça règle le problème.
8.0 pas 8.1?

**Comment by kdubuc** [comment]
Les erreurs déclenchées sont dues à des lignes de code qui ne fonctionnent qu'avec une version 8.0 de PHP. Si vous pouvez passer sur du 8.1 directement, c'est encore mieux. 😉
