### ISSUE TITLE
Problème communication avec Plat'AU : 500 Internal Server Error

### ISSUE THREAD

**Issue by CFX-SDIS33** [SDIS62/prevarisc-passerelle-platau#46]
En sachant que nous avons mis à jour notre passerelle le 13/02, nous avons rencontré l'erreur suivante `500 Internal Server Error` :
- du 29/12 au 13/02 chaque jour
- du 28/02 au 03/03
- du 16/03 au 19/03

Depuis le 15/03, nous rencontrons l'erreur suivante quotidiennement :
`Un problème est survenu lors de la requête à /mtes/platau/v9/consultations/recherche : Plat'AU a répondu avec un code 500. Nous allons attendre 1.50 secondes avant de réessayer. Ceci est l'essai numéro x`

Pour exemple, voici les logs d'appel à Plat'AU pour l'import des PJ le 19/03 (exécution de la commande 4 fois par jour) :
[2023-03-19_import_pieces_platau.log](https://github.com/SDIS62/prevarisc-passerelle-platau/files/11031623/2023-03-19_import_pieces_platau.log)

**Comment by kdubuc** [comment]
Les erreurs 500 viennent directement de Plat'AU.
Nous avons reçu pas mal de messages dernièrement nous informant que l'accès aux services Plat'AU est fortement perturbé.

Techniquement, la passerelle va faire 5 tentatives espacées dans le temps pour essayer de mitiger cela (c'est ce que l'on voit dans vos logs). Mais si le service Plat'AU n'arrive pas à répondre à nos requêtes à l'issue, la passerelle s'arrête et retourne l'erreur de la plateforme.
