### ISSUE TITLE
Consultation introuvable selon les critères de recherche

### ISSUE THREAD

**Issue by nmeucci** [SDIS62/prevarisc-passerelle-platau#48]
Bonjour, j'ai tenté d'envoyer deux avis de commission, FAV et DEF, avec une prescription pour le dernier. Dans les deux cas le connecteur lève une erreur que "la consultation est introuvable selon les critères de recherche" (et pourtant après avoir écrit dans la console "Versement d'un avis [favorable/défavorable] pour la consultation (...)" le récupérant donc bien.

La commande détails renvoie pour les deux : type "Obligatoire", état "Versée", objet "Pour avis et/ou formulation de prescriptions". Pour ce dernier point j'avais des doutes car un export d'avis sans passer de consultation en paramètre renvoie "Pas de consultations en attente d'avis". Mais visiblement la valeur correspond et il n'y a pas de blocage métier de Plat'Au a fortiori de transmission de d'avis.

**Comment by kdubuc** [comment]
y'a t'il une PEC qui a été envoyée avant l'envoi d'avis ?
