### ISSUE TITLE
Erreur 500 lors de l'import des pièces jointes de certains dossiers

### ISSUE THREAD

**Issue by CFX-SDIS33** [SDIS62/prevarisc-passerelle-platau#50]
Bonjour,

Depuis une semaine, nous rencontrons quotidiennement l'erreur suivante lors de l'import de certains dossiers.
Par exemple :
`Problème lors du traitement de la consultation : Server error: 'GET https://telechargement.platau.cohesion-territoires.gouv.fr/v9/pieces/KRX-EG0-E0K-1/contenu' resulted in a '500 Internal Server Error' response`

D'autre part, nous n'avons reçu à ce jour aucune PJ correspondant aux dossiers dont l'ID Plat'AU est le "KN5-7X8-Y0L" (consultation reçue le 05/06) et le "O3W-6Q8-ZDO" (consultation reçue le 02/06) et aucune trace non plus de ces consultations dans les logs de la passerelle lors de l'exécution de la commande d'import des PJ...

Merci d'avance de faire remonter ces deux soucis.

**Comment by CFX-SDIS33** [comment]
> D'autre part, nous n'avons reçu à ce jour aucune PJ correspondant aux dossiers dont l'ID Plat'AU est le "KN5-7X8-Y0L" (consultation reçue le 05/06) et le "O3W-6Q8-ZDO" (consultation reçue le 02/06) et aucune trace non plus de ces consultations dans les logs de la passerelle lors de l'exécution de la commande d'import des PJ...

Même souci pour les consultations dont l'ID Plat'Au est : 
- L95-RZR-6YO
- KVX-Q4Q-QVL
- KRX-YJD-Z7K

**Comment by kdubuc** [comment]
Après contact avec l'équipe Plat'AU, ils confirment les problématiques sur les imports de pièces. Patch prévu pour le 4 juillet.
