### ISSUE TITLE
Probleme Plat'au et certificat SSL

### ISSUE THREAD

**Issue by SDIS91** [SDIS62/prevarisc-passerelle-platau#51]
Bonjour

Des problèmes sont apparus sur les imports et exports de demandes:
sur les imports de pièces jointes nous avons eu le message: 

> Recherche de toutes les consultations versées (--force-non-pec) ...
> Problème lors du traitement de la consultation : Server error: `GET [https://telechargement.platau.cohesion-territoires.gouv.fr/v9/pieces/LPG-Z86-9PL-1/contenu`](https://telechargement.platau.cohesion-territoires.gouv.fr/v9/pieces/LPG-Z86-9PL-1/contenu%60) resulted in a `504 Gateway Time-out` response:
> <html><body><h1>504 Gateway Time-out</h1> The server didn't respond in time.
> </body></html>

sur les exports des pieces jointes et avis le message:

>   cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes re  
>   ceived (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https:/  
>   /api.aife.economie.gouv.fr/mtes/platau/v9/consultations/recherche?colonneTr  
>   i=DT_DEPOT&sensTri=DESC&numeroPage=0&nbElementsParPage=50

Or la semaine dernière nous avons reçu un message disant:

> Un changement du certificat public des accès à PISTE pour les API sera effectué le 04/07/2023.

Pensez-vous que ça ait un rapport avec les messages d'erreur ou est-ce une simple coïncidence?
S'il y a un rapport, pensez-vous que les actions de corrections concernent la passerelle prevarisc-plat'au ou uniquement les APIs de Piste?

Merci

**Comment by kdubuc** [comment]
avez vous encore le problème ssl ?

**Comment by SDIS91** [comment]
Bonjour

Apparemment ce changement de certificat ne concernait pas la communication avec Plat'au. C'etait seulement l’accès public au site de piste qui renouvelai son certificat.

**Comment by kdubuc** [comment]
très bien, je clos le ticket 😉
