### ISSUE TITLE
Erreur lors du HealthCheck

### ISSUE THREAD

**Issue by sdis12** [SDIS62/prevarisc-passerelle-platau#7]
Bonjour,

Suite à la mise à jour du code concernant la constante PLAUTAU_URL nous avons mis à jour le code. 
Cependant nous rencontrons toujours un problème quand nous lançon la commande Healthcheck ci dessous : 
php bin/platau --config=sdis12.json healthcheck
Le message d'erreur retourné est le suivante : 
_PHP Parse error:  syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')' in /var/www/prevarisc-passerelle-platau/src/Service/PlatauConsultation.php on line 28_

Pour info nous avons installé la passerelle platau sur un nouveau serveur pour s'affranchir des contraintes de compatibilité système de notre serveur prevarisc. Nous avons paramétré le fichier sdis12.json pour faire appel à notre bdd prevarisc.

Merci pour vos investigations.
Cordialement,

**Comment by kdubuc** [comment]
quelle est la version de PHP installée sur votre serveur ?

**Comment by sdis12** [comment]
Je suis sur du debian 10. Voici le resultat d'un php -v. Pour info j'avais la même erreur en tentant d'installer sur un centos 7.

PHP 7.3.31-1~deb10u1 (cli) (built: Oct 24 2021 15:18:08) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.31, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.31-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies

**Comment by kdubuc** [comment]
La version 7.3 de PHP n'est plus supportée : https://www.php.net/supported-versions.php.
Mettez à jour PHP à la version 7.4, ce qui résoudra le problème que vous rencontrez

**Comment by sdis12** [comment]
Ok merci pour le retour. Apres passage à php 7.4 effectivement le healthcheck fonctionne.
Peut etre il serai intéressant de mettre un section de prérequis système (OS, version php) dans la documentation d'accueil.
