### ISSUE TITLE
Questions paramétrage Platau - Prevarisc

### ISSUE THREAD

**Issue by nikown** [SDIS62/prevarisc-passerelle-platau#8]
Bonjour,
J'aurais quelques questions au sujet de la mise en place de plat'au sur un environnement Prevarisc.

Version OS: Debian 8.7
Version Prevarisc: 2.x...origin/2.x@8b972a1

J'arrive bien à télécharger l'applicatif platau que je place dans le /var/www
Cependant la commande _composer install -n --no-dev --no-suggest --no-progress --no-scripts_ me retourne un "commande introuvable". Est ce qu'il faut obligatoirement passer par cette commande ?

J'ai téléchargé et installer le composer depuis la doc d'install de leur site _https://getcomposer.org/download/_ rubrique _command line installation_ tout cela sans le répertoire plat'au.

Ma question se pose sur l'emplacement du fichier à modifier en .JSON, que je ne trouve pas. Le seul fichier s'en rapprochant (avec les paramètres de BDD de Prevarisc) est mon _prevarisc.conf_ présent dans ma conf apache2 - sites-enabled.

Merci d'avance pour votre aide.

Cordialement,
Nicolas Decor
Service SITC - SDIS11

**Comment by sdis12** [comment]
Bonjour,

Comme conseillé lors des visios et autre ticket sur le github, il vaut mieux installer le connecteur sur un nouveau serveur.
Dans ce cas partir sur un OS debian récent. 10 voir 11.
Il semble compliqué de faire tourner les 2 sur le même serveur.
Attention, pour que le connecteur fonctionne il faut un version 7.4 de PHP. En dessous ça ne fonctionne pas !

Voici un exemple de notre fichier sdis12.json (j'ai enlevé les infos confidentielles
```
{
    "platau.options": {
        "PISTE_CLIENT_ID": "CLIENT_ID_PISTE",
        "PISTE_CLIENT_SECRET": "CLIENT_SECRET",
        "PLATAU_ID_ACTEUR_APPELANT": "ID_ACTEUR"
    },
    "prevarisc.options": {
        "PREVARISC_DB_NAME": "prevarisc",
        "PREVARISC_DB_USER": "usernamedbprevarisc",
        "PREVARISC_DB_PASSWORD": "password",
        "PREVARISC_DB_HOST": "IP_SERVEUR_PREVARISC",
        "PREVARISC_DB_DRIVER": "pdo_mysql",
        "PREVARISC_DB_CHARSET": "utf8",
        "PREVARISC_DB_PORT": 3306,
        "PREVARISC_DB_PLATAU_USER_ID": 0,
        "PREVARISC_PIECES_JOINTES_PATH": "/piecesjointes"
    }
}

```
Concernant les pièces jointes le but est de monter le dossier des pièces jointes du serveur prevarisc sur le serveur dédié à platau. A vous de voir quoi utiliser en fonction d'ou son stocké vos pièce jointes prévarisc (NFS, Samba...etc).

De notre coté nous avons juste validé le connexion au connecteur avec la commande suivante (dans le dossier d'install de la passerelle /var/www/prevarisc-passerelle-platau)
 php bin/platau --config=sdis12.json healthcheck

Cordialement,

**Comment by kdubuc** [comment]
> J'arrive bien à télécharger l'applicatif platau que je place dans le /var/www Cependant la commande _composer install -n --no-dev --no-suggest --no-progress --no-scripts_ me retourne un "commande introuvable". Est ce qu'il faut obligatoirement passer par cette commande ?

Composer permet d'installer toutes les dépendances nécessaires au fonctionnement de la passerelle, c'est donc un pré-requis.
Avez vous un fichier ```composer.phar``` dans le dossier dans lequel vous avez effectué les commandes d'installation ?
 
> Ma question se pose sur l'emplacement du fichier à modifier en .JSON, que je ne trouve pas. Le seul fichier s'en rapprochant (avec les paramètres de BDD de Prevarisc) est mon _prevarisc.conf_ présent dans ma conf apache2 - sites-enabled.

C'est un fichier de la passerelle à créer, dans lequel vous devez donner toutes les informations de connexion avec Prevarisc et Plat'AU.
