### ISSUE TITLE
Comment installer le composant plateau en lien avec prevarisc

### ISSUE THREAD

**Issue by sdis12** [SDIS62/prevarisc-passerelle-platau#9]
Bonjour,

Nous arrivons à avoir un connexion avec l'api sur le serveur plateau. 
Le healthcheck renvoi un réponse correcte : 
`php bin/platau --config=sdis12.json healthcheck
RAS. Tout est disponible et prêt à l'emploi !`

La commande import fonctionne (meme si on pas encore de dossier).
`php bin/platau --config=sdis12.json import
Récupération des consultations versées  ...
Pas de consultations nous concernant. On vérifiera plus tard si il y en a de nouvelles !`

L'installation du composant semble donc ok de notre coté. Il n'y a pas d'info sur le paramétrage supplémentaire à apporter sur le serveur mais en l'état je ne vois pas comment cela va fonctionner. Nous serions tentés de mettre une tache planifié qui exécute régulièrement la tache d'import des dossiers pour que ça vienne alimenter les demandes dans prevarisc. Est ce bien cela qu'il faut mettre en place ? ce n'est pas indiqué dans la documentation.

De plus dans la documentation il est noté de passer les 2 commandes suivantes pour respectivement indiquer la prise en compte du dossier et donner l'avis de la commission : 
`$ php bin/platau --config=CHEMIN_RELATIF_VERS_LE_FICHIER_DE_CONFIGURATION.json [--consultation-id=xxx-xxx-xxx] export-pec
$ php bin/platau --config=CHEMIN_RELATIF_VERS_LE_FICHIER_DE_CONFIGURATION.json [--consultation-id=xxx-xxx-xxx] export-avis`

Est ce que la aussi on doit planifier dans un cron les 2 commandes suivantes ? 
php bin/platau --config=sdis12.json export-pec
php bin/platau --config=sdis12.json export-pec

Merci pour cette précision.
Cordialement,

**Comment by kdubuc** [comment]
Effectivement, un cron est une bonne solution pour executer de façon automatisée les commandes d'import et d'export (d'avis et de PEC). Idéalement, l'import pourrait se faire la nuit, tandis que l'export peut se réaliser le midi et le soir.

**Comment by SDIS91** [comment]
Bonjour

Merci pour le dernier commit.
Faut-il ajouter la commande de récupération des pièces jointes en tache cron à la suite de la commande d'import?
